# Generated by Django 3.2.23 on 2023-11-09 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(default='uncategorized', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='project_categories', to='blog.category'),
        ),
    ]
